export const ADD_FOLLOWING_USER_DATA = "ADD_FOLLOWING_USER_DATA";
export const UPDATE_FOLLOWING_USERS_COUNT = "UPDATE_FOLLOWING_USERS_COUNT";
export const CLEAR_USERS = "CLEAR_USERS";
export const UPDATE_FOLLOWING_USERS_ON_UNFOLLOW = "UPDATE_FOLLOWING_USERS_ON_UNFOLLOW";
export const CURRENT_USER_POST_LIKES = "CURRENT_USER_POST_LIKES";
export const ADD_FOLLOWING_USER_STORIES = "ADD_FOLLOWING_USER_STORIES";
export const UPDATE_FOLLOWING_USER_STORIES = "UPDATE_FOLLOWING_USER_STORIES";