export const ADD_FOLLOWING_USER_DATA = "FOLLOWING_USERS_DATA";
export const UPDATE_FOLLOWING_USERS_COUNT = "FOLLOWING_USERS_COUNT";
export const CLEAR_USERS = "CLEAR_USERS";
export const UPDATE_FOLLOWING_USERS_ON_UNFOLLOW = "UPDATE_FOLLOWING_USERS_ON_UNFOLLOW";